name = "edge-mail"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-12"

kv_namespaces = [
    {binding = "ACCOUNTS", id = "", preview_id = ""}
]

[build]
command = "npm install && npm test && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "MAILBOX", class_name = "Mailbox"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Mailbox"]
